name: Call PR Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  validate-pr:
    if: startsWith(github.head_ref, 'release-please--branches') == false
    uses: entur/gh-workflows/.github/workflows/pr-validation.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  pr:
    if: startsWith(github.head_ref, 'release-please--branches') == false
    uses: ./.github/workflows/helm-pr.yml
    with:
      charts: '["common"]'
