name: Call PR Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review

jobs:
  pr:
    uses: ./.github/workflows/pr-helm.yml
    with:
      charts: '["common"]'
