---
name: helm-pr

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review
    paths:
      - "charts/sausage-dispenser/**"

env:
  CHART_NAME: sausage-dispenser
  CT_CHART_DIRS: charts/

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.1

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Lint Helm
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: ct lint --check-version-increment false --charts charts/${{ env.CHART_NAME }} --target-branch ${{ github.event.repository.default_branch }}
          config: ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install --debug --charts charts/${{ env.CHART_NAME }}
