name: Call PR Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

jobs:
  main:
    uses: ./.github/workflows/publish-helm.yml
    with:
      charts: '["common"]'
