name: release - sausage dispenser

on:
  push:
    branches: [main]
    paths:
      - "charts/sausage-dispenser/**"

env:
  IMAGE_NAME: ${{ github.repository }}
  CHART_NAME: "sausage-dispenser"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: ./charts/${{ env.CHART_NAME }}/Chart.yaml
          version-path: version
          skip-ci: true
          skip-commit: false # Update versions file
          output-file: charts/${{ env.CHART_NAME }}/CHANGELOG.md
          release-count: 10
          fallback-version: "0.1.0"
          tag-prefix: "${{ env.CHART_NAME }}-"

      - name: Delete Tag
        uses: dev-drprasad/delete-tag-and-release@v0.1.3
        with:
          delete_release: true
          tag_name: ${{ steps.changelog.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-chart:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Checkout source code
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
